FROM nvidia/cuda:cudnn
MAINTAINER Yasutomo Kawanishi <yasutomo57jp@gmail.com>
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt update --fix-missing && apt install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion
RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.3.11-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda && rm ~/miniconda.sh
RUN apt install -y curl grep sed dpkg && TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o "/v.*\"" | sed 's:^..\(.*\).$:\1:'` && curl -L "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" > tini.deb && dpkg -i tini.deb && rm tini.deb

RUN apt install -y libopencv-dev

ENV PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN conda create -n alcon python=3.6 anaconda-client
RUN ["/bin/bash", "-c", "source activate alcon && conda install -y numpy scipy ipython scikit-learn scikit-image matplotlib opencv tensorflow-gpu keras"]
RUN echo "source activate alcon" >> /etc/profile.d/conda.sh

ENTRYPOINT ["/usr/bin/tini"]
CMD ["/bin/bash"]
